### ISSUE TITLE
NumerBay Model integration

### ISSUE THREAD

**Issue by CarloLepelaars** [crowdcent/numerblox#45]
The [ExternalCSVs](https://github.com/crowdcent/numerblox/blob/master/numerblox/model.py#L242) Model object in `numerblox` handles CSV submission loading from a given directory. This object can be augmented to also support downloading of external submissions from [Numerbay](https://numerbay.ai/).

1. `ExternalCSVs` could take a list of Numerbay products as an argument, automatically download them and add to `NumerFrame`. Another option would be to create a dedicated Model object like `NumerBayCSVs`.
2. Include easy Numerbay authentication with [Key object](https://github.com/crowdcent/numerblox/blob/master/numerblox/key.py).
3. Add checks to ensure NumerBay downloading is successful and gives clear error message otherwise.

NumerBay: https://numerbay.ai/

NumerBay Python API example: https://docs.numerbay.ai/docs/tutorial-extras/ensemble

**Comment by restrading** [comment]
Hi @CarloLepelaars ,

I plan to make a PR by this week that will do the following:
1. add a subclass of `ExternalCSVs` called `NumerBayCSVs` in `04_model.ipynb`
2. Init takes `data_directory` as downloading destination, `numerbay_product_names` as list of preds to download, `numerbay_username` and `numerbay_password`.
3. during `predict`, predictions are either loaded from the folder (if already download or placed manually by the user into the folder), or download from NumerBay
4. add a subclass of  `BaseSubmitter` called `NumerBaySubmitter` that takes similar auth args for init, `save_csv` submits to NumerBay to fulfill orders

Are you/crowdcent ok with the above? Also, I'm not familiar with nbdev, do you require me to write mock test for this (without actual numerbay account)? If writing test is not required, I can make sure the code is correct locally.

**Comment by restrading** [comment]
Hi @CarloLepelaars ,

Before creating a merge request, I hope you could take a look at the code at [here](https://github.com/restrading/numerblox/blob/feature/numerbay-integration/nbs/04_model.ipynb) and [here](https://github.com/restrading/numerblox/blob/feature/numerbay-integration/nbs/09_submission.ipynb) for a sanity check. Thanks.

A few things to note:
1. The submitter took a wrapper aproach that uses a tournament submitter. User can choose to submit to both Numerai and NumerBay or NumerBay only
2. The `NumerBayCSVs` currently only supports the classic tournament. The `ExternalCSVs` also doesn't seem to support Signals, and I wrote some workarounds initially but the code got hacky quickly because the prediction files can be flexible in number of columns, column names and column types. I think these could be better handled in the NumerFrame itself (cleaning, casting and nan-filling for the Signals meta columns). However, I don't have capacity to work on this for this week.
3. The github workflow is failing by throwing `Dataset 'numerai_validation_data.parquet' not available in NumerAPI`. I don't have extra time this week to fix this.
4. Other than above, the two components have been tested locally, the code is included in the notebooks as comments. The underlying numerbay api is tested in the `numerbay-api` package itself.

**Comment by CarloLepelaars** [comment]
Very cool, @restrading! 

1. So do I understand it correctly `NumerBaySubmitter` will mainly make it easy for prediction sellers to upload to NumerBay and submit their models? Really like this as long as communicate that NumerBay prediction buyers should refer to `NumerBayCSVs` and go from there.

2. Good point that `ExternalCSVs` does not support Signals, because we are only adding the prediction column. I'll have a look if this can be generalized. I'll think about if we can clean this up or abstract away some components in the base class. Great suggestion to handle that within the `NumerFrame`. I'll definitely check out what we can do there!

3. Great to hear that it already works well locally, trust you on this!

4. Do you think it would also be nice to support downloading of Signals data from NumerBay? I saw around [5 listings of these on the website](https://numerbay.ai/explore/signals-data).

**Comment by restrading** [comment]
Thanks for the reply. Great job for the NumerCon presentation!

1. Yes. A seller can simply wrap a NumerBaySubmitter outside of the tournament submitters that their already use to submit to both sites. Of course they can also submit to NumerBay only (if they want to separate the pipelines or do re-submissions) by turning off `upload_to_numerai`.
2. Yes and I think it might be needed for NumerFrame to introduce some opinions (e.g. always convert friday_date to int if it's a date obj, always fill missing friday_date with the previous friday, etc.)
3. Thanks but bugs might be inevitable at some point :)
4. For now I think catering to the prediction blending needs would suffice. There has not been active uploads for the Signals data category. I plan to introduce some Signals data-specific features to NumerBay in the near term to drive usage.

**Comment by restrading** [comment]
#59 Created a PR
