### ISSUE TITLE
Make some deps optional

### ISSUE THREAD

**Issue by restrading** [crowdcent/numerblox#73]
Currently, a fresh installation of numerblox requires downloading all of the machine learning libraries in the dependency. This can be too heavy weight for simple use cases (e.g. if I only want to use numerblox for downloading preds and post ensembling, I don't need to install tensorflow just for that)

So I would suggest some of the heavy ML libraries could be made optional. This is just a suggestion, I'm not sure the best way to do it.

**Comment by CarloLepelaars** [comment]
Hi Ryan, thanks for the suggestion! Unfortunately it seems tricky to make these dependencies optional. Several models and postprocessors rely on Tensorflow. It sounds annoying if people run into error messages due to an incomplete installation.
Currently there is 1 optional dependency (`TA-Lib`), because it requires C bindings and takes quite a while to install. Using things like `TalibFeatureGenerator` requires you to install TA-Lib separately. 

Another downside is that if we make several installable dependency sets we would have to run testing for these different versions. The complexity increases really quickly.

I hope this explains the situation clearly. I'm open to good ideas to optimize the installation process.
